version: "3.9"

services:
  backend:
    build: ./server
    container_name: ai-support-backend
    ports:
      - "5000:5000"
    env_file:
      - ./server/.env

  frontend:
    build: ./client
    container_name: ai-support-frontend
    ports:
      - "3000:80"
    depends_on:
      - backend
